/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package front;

import java.util.List;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import objects.Cliente;

/**
 *
 * @author heftyn
 */
public class PopUpClientes extends javax.swing.JFrame {

    private List<Cliente> clientes;
    private JTable tabla;
    private ClienteTableModel tableModel;
    
    /**
     * Creates new form PopUpAlumnos
     */
    public PopUpClientes() {
        initComponents();
        setearTabla();
    }

    /**
     * Creates new form PopUpAlumnos
     */
    public PopUpClientes(List<Cliente> cli) {
        clientes = cli;
        initComponents();
        setearTabla();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        scpAlumnos = new javax.swing.JScrollPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("CLIENTES");
        setAlwaysOnTop(true);
        setType(java.awt.Window.Type.POPUP);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scpAlumnos, javax.swing.GroupLayout.DEFAULT_SIZE, 397, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scpAlumnos, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    void setClientes(List<Cliente> clientes) {
        
        this.clientes = clientes;
        tableModel.fireTableDataChanged();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane scpAlumnos;
    // End of variables declaration//GEN-END:variables

    private void setearTabla() {
        tabla = new JTable();
        scpAlumnos.setViewportView(tabla);
        tableModel = new ClienteTableModel();
        tabla.setModel(tableModel);
    }
    
    private class ClienteTableModel extends DefaultTableModel
    {
        @Override
        public Object getValueAt(int row, int col) 
        {
            Object value = null;
            if (row >= 0 && clientes != null)
            {
                Cliente cliente = clientes.get(row);
                switch (col)
                {
                    case 0:
                    {
                        value = cliente.getEstado().name();
                        break;
                    }
                    case 1:
                    {
                        value = cliente.getRegreso().name();
                        break;
                    }
                    case 2: 
                    {
                        value = cliente.getHora_regreso_sistema();
                        if (value instanceof Double && ((Double)value) == Double.MAX_VALUE)
                        {
                            value = Double.valueOf(0);
                        }
                        break;
                    }
                    case 3:
                    {
                        value = cliente.getTiempo_esperando();
                        if (value instanceof Double && ((Double)value) == Double.MAX_VALUE)
                        {
                            value = Double.valueOf(0);
                        }
                        break;
                    }
                }
            }
            return value;
        }
            
        @Override
        public int getRowCount() {
            return clientes != null ? clientes.size() : 0;
        }

        @Override
        public int getColumnCount() {
            return 4;
        }

        @Override
        public String getColumnName(int columnIndex) {
            String colName ="";
            switch (columnIndex)
            {
                case 0:
                {
                    colName = "Estado";
                    break;
                }
                case 1:
                {
                    colName = "Ha regresado?";
                    break;
                }
                case 2:
                {
                    colName = "Hora regreso";
                    break;
                }
                case 3:
                {
                    colName = "Tiempo Esperando";
                    break;
                }
            }
            return colName;
        }

        @Override
        public Class<?> getColumnClass(int columnIndex) {
            switch (columnIndex)
            {
                case 0:
                {
                    return String.class;
                }
                case 1:
                {
                    return String.class;
                }
                case 2:
                {
                    return Double.class;
                }
                case 3:
                {
                    return Double.class;
                }
            }
            return Class.class;
        }

        @Override
        public boolean isCellEditable(int rowIndex, int columnIndex) {
            return false;
        }
    }
}
